import type { Finding, MemberProfile, RepairStep } from "@/lib/engine/types";
import { formatIndianDate, formatRupees } from "@/lib/engine/dates";

/**
 * Document drafting.
 *
 * These are built from deterministic templates, not generated by a model, and
 * that is a deliberate choice. A Joint Declaration with a hallucinated field or
 * a grievance citing a paragraph that does not exist is worse than no document
 * at all — it gets rejected, and the member has burned three weeks discovering
 * it. Templates are auditable and always available.
 *
 * The model's job (src/lib/translate.ts) is to render these into the member's
 * language and read them aloud. That is a task where being approximately right
 * is genuinely useful, which drafting a legal instrument is not.
 */

export type DocumentKind = NonNullable<RepairStep["generates"]>;

export interface GeneratedDocument {
  kind: DocumentKind;
  title: string;
  /** Who this is addressed to, in the member's words. */
  audience: string;
  /** How the member actually gets this in front of the right person. */
  delivery: string[];
  /** The document body. Monospace, copyable, printable. */
  body: string;
  /** What the member should keep after sending, and why. */
  keep?: string;
}

function header(m: MemberProfile, asOf: string): string {
  return [
    `Date: ${formatIndianDate(asOf)}`,
    ``,
    `Member name (as per EPFO): ${m.epfoName}`,
    `UAN: ${m.uan}`,
    `Date of birth (as per EPFO): ${formatIndianDate(m.epfoDob)}`,
  ].join("\n");
}

function jointDeclaration(m: MemberProfile, asOf: string): GeneratedDocument {
  const corrections: Array<[string, string, string]> = [];
  if (m.epfoName !== m.aadhaarName) corrections.push(["Name", m.epfoName, m.aadhaarName]);
  if (m.epfoDob !== m.aadhaarDob)
    corrections.push(["Date of birth", formatIndianDate(m.epfoDob), formatIndianDate(m.aadhaarDob)]);
  if (m.epfoFatherName !== m.aadhaarFatherName)
    corrections.push(["Father's / husband's name", m.epfoFatherName, m.aadhaarFatherName]);
  if (m.epfoGender !== m.aadhaarGender) corrections.push(["Gender", m.epfoGender, m.aadhaarGender]);

  const rows = corrections
    .map(([field, from, to], i) => `  ${i + 1}. ${field}\n       Currently in EPFO record : ${from}\n       Correct value (per Aadhaar): ${to}`)
    .join("\n\n");

  return {
    kind: "JOINT_DECLARATION",
    title: "Joint Declaration for correction of member details",
    audience: "Your employer, who signs it with you and submits it to EPFO",
    delivery: [
      "Print two copies. Sign both.",
      "Give both to your employer's HR or accounts department and ask them to sign and submit through their EPFO login.",
      "Ask for one signed copy back with the date on it. This is your proof that you asked.",
      "The employer's submission is what reaches EPFO — a copy you submit yourself will not be actioned.",
    ],
    keep: "Keep the signed copy. If the employer does not act within fifteen days, it is the evidence your grievance rests on.",
    body: [
      `JOINT DECLARATION BY THE MEMBER AND THE EMPLOYER`,
      `(For correction of member details in the EPFO database)`,
      ``,
      header(m, asOf),
      ``,
      `Establishment: ${m.spells[0]?.employerName ?? "—"}`,
      `Establishment code: ${m.spells[0]?.establishmentId ?? "—"}`,
      ``,
      `We jointly declare that the following particulars in the EPFO record are`,
      `incorrect and request that they be corrected as shown, supported by the`,
      `Aadhaar record enclosed:`,
      ``,
      rows || `  (No mismatches detected on this record.)`,
      ``,
      `The correction sought is a correction of a clerical discrepancy only. The`,
      `identity of the member is not in question and no change of membership is`,
      `sought.`,
      ``,
      `Enclosed: self-attested copy of Aadhaar; self-attested copy of PAN (if`,
      `available); a document evidencing date of birth.`,
      ``,
      ``,
      `_______________________         _______________________`,
      `Signature of the member          Signature and seal of`,
      `${m.epfoName.padEnd(32)}the employer`,
    ].join("\n"),
  };
}

function employerExitRequest(m: MemberProfile, asOf: string): GeneratedDocument {
  const spell = m.spells.find((s) => s.doe === null) ?? m.spells[0];
  const lastDay = m.unemployedSince ? formatIndianDate(m.unemployedSince) : "____________";

  return {
    kind: "EMPLOYER_EXIT_REQUEST",
    title: "Request to your employer to mark your date of exit",
    audience: `The HR or accounts department at ${spell?.employerName ?? "your last employer"}`,
    delivery: [
      "Send this by email if you have an address for HR — an email is dated and cannot be denied later.",
      "If you only have WhatsApp, send it there and screenshot the delivery.",
      "If you go in person, take a printed copy and ask them to sign a duplicate as acknowledgement.",
      "Note the date you sent it. Fifteen days from that date is when you escalate.",
    ],
    keep: "Keep the sent email or the acknowledged copy. Without a dated request, EPFO treats an employer's inaction as your delay.",
    body: [
      `Subject: Request to update date of exit in EPFO records — UAN ${m.uan}`,
      ``,
      `To the HR / Accounts Department`,
      `${spell?.employerName ?? "—"}`,
      `Establishment code: ${spell?.establishmentId ?? "—"}`,
      ``,
      header(m, asOf),
      ``,
      `Sir / Madam,`,
      ``,
      `I was employed with the establishment and my last working day was`,
      `${lastDay}. My EPFO record still shows me as being in continuing`,
      `service, because the date of exit has not been updated.`,
      ``,
      `Because of this, I am unable to file for settlement of my provident fund.`,
      `Any claim I submit is rejected with the reason "member is still in`,
      `service".`,
      ``,
      `I request you to update my date of exit in the EPFO employer portal, under`,
      `the exit-date facility available in the establishment login. The reason to`,
      `be recorded is cessation of employment.`,
      ``,
      `I would be grateful if this is done within fifteen days. If it is not`,
      `possible for any reason, I would request a brief note in writing telling me`,
      `why, so that I can take the matter up with the regional office.`,
      ``,
      `Thank you.`,
      ``,
      `${m.epfoName}`,
      `UAN ${m.uan}`,
    ].join("\n"),
  };
}

function uanMergeRequest(m: MemberProfile, asOf: string): GeneratedDocument {
  return {
    kind: "UAN_MERGE_REQUEST",
    title: "Request to merge your old PF accounts into one",
    audience: "The EPFO regional office holding your current account",
    delivery: [
      "The fastest route is the member portal itself: Online Services → One Member One EPF Account (Transfer Request).",
      "File one request per past employer. Each is approved separately.",
      "Use this letter only if the online transfer fails or an old UAN does not appear at all.",
    ],
    keep: "Note each transfer request's tracking number. Service that is not transferred does not count towards the ten years pension needs.",
    body: [
      `Subject: Request for transfer and merger of previous PF accounts — UAN ${m.uan}`,
      ``,
      `To the Regional Provident Fund Commissioner`,
      ``,
      header(m, asOf),
      ``,
      `Sir / Madam,`,
      ``,
      `The following Universal Account Numbers stand in my name and have not been`,
      `merged with the UAN I currently use:`,
      ``,
      ...m.unmergedUans.map((u, i) => `  ${i + 1}. ${u}`),
      ``,
      `My employment history is as follows:`,
      ``,
      ...m.spells.map(
        (s, i) =>
          `  ${i + 1}. ${s.employerName} (${s.establishmentId})\n       ${formatIndianDate(s.doj)} to ${s.doe ? formatIndianDate(s.doe) : "continuing"}${s.transferredIntoCurrentUan ? "" : "  — NOT YET TRANSFERRED"}`,
      ),
      ``,
      `Because the service is recorded against separate account numbers, my total`,
      `service is understated. This affects my eligibility for pension, which`,
      `requires ten years of service, and the tax treatment of any withdrawal.`,
      ``,
      `I request that the above accounts be transferred and merged into UAN`,
      `${m.uan}, and that my total service be recomputed accordingly.`,
      ``,
      `${m.epfoName}`,
      `UAN ${m.uan}`,
    ].join("\n"),
  };
}

function grievance(m: MemberProfile, finding: Finding, asOf: string): GeneratedDocument {
  const spell = m.spells[0];
  const gaps = m.spells.flatMap((s) => s.contributionGapMonths);

  // The grievance body adapts to the finding it was raised from, because a
  // generic "please help" grievance is closed with a generic reply. Naming the
  // specific default, and the provision it breaches, is what forces an answer.
  const specifics: string[] =
    finding.ruleId === "SERVICE_CONTRIBUTION_GAP"
      ? [
          `Provident fund was deducted from my wages for the following months, but`,
          `no corresponding remittance appears in my account:`,
          ``,
          ...gaps.map((g, i) => `  ${i + 1}. ${g}`),
          ``,
          `I enclose the wage slips for those months, which show the deduction.`,
          ``,
          `Deducting an employee's contribution and failing to remit it is not a`,
          `delay in administration. I request that the establishment be directed to`,
          `remit the amount with interest and damages, and that the months be`,
          `credited to my service.`,
        ]
      : finding.ruleId === "SERVICE_EXIT_DATE_MISSING"
        ? [
            `My last working day at ${spell?.employerName ?? "the establishment"} was`,
            `${m.unemployedSince ? formatIndianDate(m.unemployedSince) : "____________"}. The`,
            `establishment has not updated my date of exit despite a written request`,
            `sent by me on ____________, a copy of which is enclosed.`,
            ``,
            `As a result my provident fund cannot be settled. I request that the`,
            `regional office update the date of exit on the basis of the last`,
            `contribution received (${spell?.lastContributionMonth ?? "—"}), or direct the`,
            `establishment to do so.`,
          ]
        : finding.ruleId === "DATA_EPS_WAGE_INCONSISTENT"
          ? [
              `My claim has been held up with the reason "wages more than 15000 / EPS`,
              `membership not applicable". This is a discrepancy in EPFO's own record`,
              `between the pension-scheme flag and the wage reported in the ECR, not`,
              `anything within my control.`,
              ``,
              `I request that the record be reconciled and the claim processed. I`,
              `enclose the wage slip for my month of joining.`,
            ]
          : [
              `The following issue is preventing settlement of my claim:`,
              ``,
              `  ${finding.title}`,
              ``,
              `I request that it be examined and resolved so that my claim can be`,
              `processed.`,
            ];

  return {
    kind: "GRIEVANCE",
    title: "Grievance to EPFO",
    audience: "EPFiGMS, the EPFO grievance system, or CPGRAMS if that fails",
    delivery: [
      "File at the EPFO grievance portal (EPFiGMS) choosing the grievance category that matches — not 'Others', which routes to a general desk and is closed with a template reply.",
      "Attach every document named in the text. A grievance without attachments is closed for want of information.",
      "Note the registration number. If there is no substantive reply in thirty days, escalate the same text to CPGRAMS quoting that number.",
    ],
    keep: "Keep the registration number and the closure remarks. If the closure does not address what you asked, that is the basis for an appeal to the Appellate Authority.",
    body: [
      `Subject: ${finding.title} — UAN ${m.uan}`,
      ``,
      header(m, asOf),
      ``,
      `Establishment: ${spell?.employerName ?? "—"} (${spell?.establishmentId ?? "—"})`,
      ``,
      `Sir / Madam,`,
      ``,
      ...specifics,
      ``,
      `EPFO's Citizen's Charter commits to settling a complete claim within twenty`,
      `days. I request that this grievance be resolved within that period, and`,
      `that I be informed in writing of the action taken rather than only of the`,
      `closure of this grievance.`,
      ``,
      `${m.epfoName}`,
      `UAN ${m.uan}`,
      ``,
      `Enclosures: as listed above.`,
    ].join("\n"),
  };
}

function kycChecklist(m: MemberProfile): GeneratedDocument {
  const items: string[] = [];
  if (m.aadhaarKyc !== "VERIFIED") items.push(`Aadhaar — currently ${m.aadhaarKyc.toLowerCase()}. Needs employer approval after you add it.`);
  if (m.panKyc !== "VERIFIED") items.push(`PAN — currently ${m.panKyc.toLowerCase()}. Without it, tax is deducted at 20% on withdrawals under five years' service.`);
  if (m.bank.status !== "VERIFIED") items.push(`Bank account ending ${m.bank.accountNumber.slice(-4)} — currently ${m.bank.status.toLowerCase()}. Needs a cheque leaf or passbook page showing your printed name.`);
  if (m.bank.ifscBelongsToMergedBank) items.push(`IFSC ${m.bank.ifsc} belongs to a merged bank. Get the current code from your passbook or bank app.`);
  if (!m.mobileLinkedToAadhaar) items.push(`No mobile number registered against your Aadhaar. Nothing can be filed without it — the OTP goes to the Aadhaar-registered number, not the one on your EPFO profile.`);
  if (!m.eNominationFiled) items.push(`No nominee on record. Ten minutes now saves your family a court certificate later.`);

  return {
    kind: "KYC_CHECKLIST",
    title: "What to carry, and what to fix first",
    audience: "You — take this to a cyber café or CSC if you are being helped",
    delivery: [
      "Do these in order. Each one that needs employer approval should be submitted on the same day, so the employer approves everything in one sitting.",
    ],
    body: [
      `KYC AND RECORD CHECKLIST`,
      ``,
      header(m, new Date().toISOString().slice(0, 10)),
      ``,
      `Balance in account: ${formatRupees(m.pfBalance)}`,
      ``,
      items.length
        ? items.map((it, i) => `  ${i + 1}. ${it}`).join("\n\n")
        : `  Nothing outstanding. Your record is complete.`,
      ``,
      `Documents to carry:`,
      `  - Aadhaar card (original and a self-attested copy)`,
      `  - PAN card, if you have one`,
      `  - Bank passbook or a cancelled cheque with your name printed on it`,
      `  - Any payslip from your last employer`,
      `  - The mobile phone with the number registered against your Aadhaar`,
    ].join("\n"),
  };
}

export function generateDocument(
  kind: DocumentKind,
  member: MemberProfile,
  finding: Finding,
  asOf: string,
): GeneratedDocument {
  switch (kind) {
    case "JOINT_DECLARATION":
      return jointDeclaration(member, asOf);
    case "EMPLOYER_EXIT_REQUEST":
      return employerExitRequest(member, asOf);
    case "UAN_MERGE_REQUEST":
      return uanMergeRequest(member, asOf);
    case "GRIEVANCE":
      return grievance(member, finding, asOf);
    case "KYC_CHECKLIST":
      return kycChecklist(member);
  }
}

/**
 * Grievance for a claim that has sat past EPFO's own twenty-day commitment.
 *
 * Kept separate from the finding-driven grievances above because this one is not
 * about a defect in the member's record — the claim was correct. It is about the
 * office having exceeded its own charter, which is a different argument and
 * needs the specific escalation ladder rather than a general request for help.
 */
export function delayGrievance(
  m: MemberProfile,
  opts: { reference: string; daysElapsed: number; formName: string; amount: number; asOf: string },
): GeneratedDocument {
  return {
    kind: "GRIEVANCE",
    title: `Escalation: ${opts.daysElapsed} days without settlement`,
    audience: "EPFiGMS first. If the reply is a closure without action, CPGRAMS, then the Appellate Authority.",
    delivery: [
      "File on EPFiGMS under the grievance category for delay in settlement of claim — not 'Others'.",
      "Quote the claim reference number in the subject line. A grievance without it is matched to nothing.",
      "If the grievance is closed without the claim actually being settled, escalate the same text to CPGRAMS quoting the EPFiGMS number, and say that the earlier grievance was closed without action.",
      "Keep the closure remarks from every round. An appeal to the Appellate Authority rests on them.",
    ],
    keep: "Every registration number and every closure note. The pattern of closures without action is the case.",
    body: [
      `Subject: Delay beyond twenty days in settlement of ${opts.formName} claim — reference ${opts.reference}, UAN ${m.uan}`,
      ``,
      header(m, opts.asOf),
      ``,
      `Claim reference: ${opts.reference}`,
      `Claim type: ${opts.formName}`,
      `Amount claimed: ${formatRupees(opts.amount)}`,
      `Working days elapsed since filing: ${opts.daysElapsed}`,
      ``,
      `Sir / Madam,`,
      ``,
      `The above claim was filed complete, with all KYC verified, and has now been`,
      `pending for ${opts.daysElapsed} working days.`,
      ``,
      `EPFO's Citizen's Charter commits to settling a complete claim within twenty`,
      `days of receipt. That period has passed. I have received no communication`,
      `stating any deficiency in the claim, and the portal continues to show it as`,
      `under process without indicating what is awaited or from whom.`,
      ``,
      `I request:`,
      ``,
      `  1. That the claim be settled forthwith.`,
      `  2. That I be informed, in writing, of the reason for the delay and the`,
      `     date on which the file was received at each stage.`,
      `  3. That interest for the period of delay be considered in accordance with`,
      `     the applicable provisions, the delay not being attributable to me.`,
      ``,
      `I would be grateful for a reply on the substance of this grievance rather`,
      `than a closure intimation.`,
      ``,
      `${m.epfoName}`,
      `UAN ${m.uan}`,
    ].join("\n"),
  };
}
